Add photon search capability
ZeLonewolf/openstreetmap-americana pull request #160
Opened 2022-02-14 03:44 UTC by ZeLonewolf

This PR adds a search box to the demo map.  This basic capability is intended to make navigation more convenient to contributors, in order to avoid manually panning and zooming the map to locations of interest.  If anyone would like to improve upon my amateur attempts, help is welcome :)

Remaining issues:

- [ ] Map loses focus after re-centering to search result
- [ ] Make search results clickable so it works with mouse/mobile, not just keyboard

![image](https://user-images.githubusercontent.com/3254090/153796054-d3e43f4a-9096-41a4-8ab8-f515be96fdab.png)

2022-02-24 03:51 UTC, ZeLonewolf commented
PR is ready for review.  Not sure if this is actually the best way to do this or if the search code should go in a subfolder.  Thoughts?

2022-02-24 21:18 UTC, jleedev requested changes
Bugs:

* When the keyboard opens and closes, the map resizes. Causes it to fly to a squished bbox.
* (Firefox Android) Tapping a result from the list causes the list to hide and reappear.
* Typing quickly causes the results to race, settling on search results for not the current query.
* Up and down arrow keys cause the text cursor to jump to the beginning/end of the search box.

Do you want to implement this as a [control](https://maplibre.org/maplibre-gl-js-docs/api/markers/#icontrol)? Will probably be better than absolutely positioning it around the other controls, it will appear simultaneously with the other controls instead of earlier, it doesn't have to access the `map` as a global variable.

2022-02-24 21:18 UTC, jleedev commented on style/index.html
> +      <div id="geocoder-live-results" />
This is incorrect for elements which are not self-closing in HTML5.

```suggestion
      <div id="geocoder-live-results"></div>
```

2022-02-24 21:18 UTC, jleedev commented on style/search.js
> +    .then((data) => geocoderResponse(data));
I'd suggest writing this with async/await, but it also needs updated to cancel all but the most recent request.

2022-02-24 21:18 UTC, jleedev commented on style/search.js
> +  e = e || window.event;
What needs this?

2022-02-24 21:18 UTC, jleedev commented on style/search.css
> +}
Suggest having `.gc-result-item` on always and toggling the class `.gc-result-item-selected` only the values to change (background-color).

2022-02-24 21:18 UTC, jleedev commented on style/search.js
> +  }
```suggestion
  if (priorIndex >= 0) {
    liveResults.children[priorIndex].classList.remove("gc-result-item-selected");
  }
  if (resultSelectIndex >= 0) {
    liveResults.children[resultSelectIndex].classList.add("gc-result-item-selected");
  }
```

2022-02-26 02:33 UTC, ZeLonewolf commented on style/search.js
> +  switch (e.keyCode) {
Looks like IE is the only outlier that doesn't support the replacement `code`, which has just [0.45% market share](https://gs.statcounter.com/browser-market-share).  I'm pretty comfortable using the newer variant.

2022-02-26 20:06 UTC, jleedev commented
> Not sure if this is actually the best way to do this or if the search code should go in a subfolder. Thoughts?

Ideally there would be some distinction between "the demo map" and "the style, which is also available standalone", but the latter really doesn't exist yet as a thing, so there's not a lot of reason to reorganize the code as such.

2022-02-27 22:28 UTC, jleedev commented
The implementation as a control is brittle as it depends on markup existing in the document. Would be more proper to create the dom nodes in the onAdd method.

2022-02-28 01:43 UTC, jleedev commented on style/search.js
> +      break;
Prevent up/down going to beginning/end of text box.

```suggestion
    case "ArrowUp":
      // up arrow
      resultSelectIndex--;
      e.preventDefault();
      break;
    case "ArrowDown":
      // down arrow
      resultSelectIndex++;
      e.preventDefault();
      break;
```

2022-02-28 01:52 UTC, jleedev approved these changes
Pretty good!

Some minor issues remain, reiterating here:

- When the keyboard opens and closes, the map resizes. Causes it to fly to a squished bbox.
- (Firefox Android) Tapping a result from the list causes the list to hide and reappear.
- The use of `id` attributes in what should technically be an instanceable control is invalid if you end up with two of them, but those ids are only used for CSS purposes, so nothing should be broken.

I'm willing to ship this in its current state.

2022-03-01 01:43 UTC, merged