Add Manitoba shields
ZeLonewolf/openstreetmap-americana pull request #272
Opened 2022-04-07 22:05 UTC by claysmalley

Fixes #229.

![Screenshot from 2022-04-07 17-52-03](https://user-images.githubusercontent.com/1732117/162326094-a3e84cd8-4cca-4bfa-8403-3994473e5c4f.png)
![Screenshot from 2022-04-07 17-51-17](https://user-images.githubusercontent.com/1732117/162326091-24c49e5f-1b65-4383-a3be-7fa5ef7ac549.png)

For Provincial Trunk Highways (`network=CA:MB:PTH`), the text "Manitoba" is removed. Letter suffixes are given the same font size as the rest of the ref, and a wider 3-character variant is introduced.

![Manitoba_Highway_15](https://user-images.githubusercontent.com/1732117/162326719-cd38a972-2849-4f97-a7ad-89502c0dfc2d.svg)
![Manitoba_Highway_83A](https://user-images.githubusercontent.com/1732117/162326718-40969a80-8576-4fbe-8b9b-3bb411137fee.svg)

For Provincial Roads, (`network=CA:MB:PR`), the text "Manitoba" is removed as well as the border, leaving just the black oval.

![Manitoba_secondary_207](https://user-images.githubusercontent.com/1732117/162326717-f2c542b7-609f-4bff-9df3-2c793ab7de22.svg)

For Winnipeg city routes (`network=CA:MB:Winnipeg`), the text "Route" is removed and the colo(u)rs are adjusted to match the existing palette.

![Winnipeg_city_route_115](https://user-images.githubusercontent.com/1732117/162326720-a0266d4b-336c-49b9-b07e-14e436b31902.svg)

2022-04-08 15:23 UTC, Pengor requested changes
One thing I might add is rounded corners at the top two nodes of the green trapezoid and bottom two nodes of the black trapezoid

2022-04-08 15:23 UTC, Pengor commented on style/icons/shield40_ca_mb_winnipeg.svg
> + <path d="m 0.5,0.5 0.6315789,3 H 24.868421 L 25.5,0.5 Z" fill="#fff" stroke="#000" style="fill:#006747;fill-opacity:1;stroke:#006747;stroke-opacity:1"/>
```suggestion
 <path d="m 0.5,0.5 0.6315789,3 H 24.868421 L 25.5,0.5 Z" fill="#006747" stroke="#006747"/>
```
Looks like there's some unused style info here that can go away

2022-04-08 15:23 UTC, Pengor commented on style/icons/shield40_ca_mb_winnipeg.svg
> + <path style="fill:none;fill-rule:evenodd;stroke:#000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" d="m 25.5,0.5 v 0"/>
```suggestion
```
It doesn't look like this path actually draws anything and can be removed

2022-04-08 17:12 UTC, ZeLonewolf commented
Test and looks good from a visual perspective.

2022-04-08 19:55 UTC, claysmalley commented
Rounded the corners of the Winnipeg shield, and removed unnecessary SVG elements and attributes.

![Screenshot from 2022-04-08 15-52-13](https://user-images.githubusercontent.com/1732117/162517120-6ff47a43-be30-4483-accc-6e308529c3a9.png)
![Screenshot from 2022-04-08 15-51-45](https://user-images.githubusercontent.com/1732117/162517116-75ed1d57-ce85-4f63-a146-afee8ebc5cb5.png)

2022-04-08 19:57 UTC, ZeLonewolf approved these changes

2022-04-08 21:22 UTC, 1ec5 approved these changes

2022-04-09 23:30 UTC, claysmalley commented
Were we waiting on anything before merging this?

2022-04-10 00:27 UTC, ZeLonewolf commented
I resolved conflicts but didn't have the chance to confirm I didn't break anything.

2022-04-10 02:32 UTC, merged