Add styling for (non-protected-area) parks
ZeLonewolf/openstreetmap-americana pull request #306
Opened 2022-05-06 03:52 UTC by AnonymousAlligatorOSM

These [are tagged](https://openmaptiles.org/schema/#fields) in OpenMapTiles in the landcover layer with subclass=park, not in the park layer (which is just for protected areas).

![Screenshot from 2022-05-05 22-48-36](https://user-images.githubusercontent.com/101657206/167063984-26059034-9aec-4eca-98c9-e499d1c9a618.png)

![Screenshot from 2022-05-05 22-48-55](https://user-images.githubusercontent.com/101657206/167063990-feb2fc4d-925f-454e-aaba-3618f5513512.png)

2022-05-06 22:29 UTC, ZeLonewolf commented
Also, please do an `npm run code_format` and commit to clear the failed lint check.

2022-05-07 18:31 UTC, claysmalley commented
I like the idea of styling parks and protected areas similarly.

That said, how come protected areas have labels and parks don't?

2022-05-07 22:08 UTC, ZeLonewolf commented
That's a good point.  We should probably copy whatever we're using for labelling protected areas and do the same with parks.

2022-05-08 01:09 UTC, AnonymousAlligatorOSM commented
> That said, how come protected areas have labels and parks don't?

Protected area names are in the `parks` layer, but park names are in the `poi` layer.

2022-05-08 01:15 UTC, ZeLonewolf commented
Yup, can confirm:
![image](https://user-images.githubusercontent.com/3254090/167277685-c7e95bd7-cd6b-47f9-9bd3-bef6b0f73dd1.png)

2022-05-08 09:30 UTC, ZeLonewolf requested changes
Please add a name label from the poi layer, `class=park`, with the same styling used in protected area labels.

2022-05-08 20:19 UTC, AnonymousAlligatorOSM commented
Added labels, although they don't show up until zoom level 14 in the tiles.

2022-05-08 20:30 UTC, ZeLonewolf commented
Screen shot of NYC at z14:
![image](https://user-images.githubusercontent.com/3254090/167314688-eb098ff0-f859-4432-9fb3-c56548a9b47e.png)

2022-05-08 20:33 UTC, ZeLonewolf approved these changes
The labelling situation is not great, but that's a limit of OpenMapTiles, which labels these features as POIs (point and label) rather than as areas.  Therefore maplibre has no way of knowing that certain parks are big and others are small in order to influence render decisions.  This will be improved when we can implement an improved parks & protected areas layers.

Given the limitation in the underlying data source, I think this is the best we're able to with OpenMapTiles.

2022-05-08 20:34 UTC, ZeLonewolf commented
I've documented a ticket to consolidate park features in OpenMapTiles in the next major revision at openmaptiles/openmaptiles#1387

2022-05-08 20:34 UTC, merged