Updated CONTRIBUTE.md to reflect that project can run on Windows
ZeLonewolf/openstreetmap-americana pull request #398
Opened 2022-06-12 07:01 UTC by bgo-eiu

From what I can see the previous information that the project cannot run on Windows due to dependency issues was resolved in #374. I cloned and installed the dependencies, and was able to run the project on Windows without issues just now, so this is just an update to the CONTRIBUTE.md to reflect that this is fixed.

I added a note about telling npm where to find `bash.exe` since that can cause issues on `npm start`.

2022-06-12 16:14 UTC, claysmalley commented
`npm run code_format` will fix the lint check.

Someone with Windows on their machine will have to review this one :sweat_smile:

2022-06-12 17:17 UTC, jleedev commented
I've heard of https://www.npmjs.com/package/shx for writing script commands (such as `rm`).

2022-06-12 20:43 UTC, bgo-eiu commented
Ran the `code_format` script, looked like I just left some trailing whitespace in the markdown file

The shx package is good to know about if it makes it any more convenient to run on windows, although I'm not sure how extensively the scripts in the project rely on bash

2022-06-12 21:00 UTC, zekefarwell commented
I tested this out on Windows and it works fine, but I figured I'd see how adding shx works in #403 too.  This makes it so the project can be run in PowerShell, the standard Windows CMD prompt, a Windows bash emulator, or WSL.   With that added, I think we can simplify the Windows specific notes to basically just say "it works on Windows", or even just remove them.

2022-06-12 21:03 UTC, zekefarwell commented
I think with #374 merged, we can remove the second about Apple Silicon/ARM Macs too.  @adamfranco can you confirm that workarounds are no longer necessary there?

2022-06-12 23:39 UTC, ZeLonewolf requested changes
Please update to be consistent with #403.

When merged, it will be possible to build on Windows as long as npm is installed.

2022-06-13 04:54 UTC, bgo-eiu commented
Now updated. I opted to just say it now runs on Windows, with parenthetical links to the issues which addressed. (It may still be helpful for people who have seen the previous Contributing page to see exactly what changed to make it work.)

2022-06-14 02:10 UTC, zekefarwell approved these changes
Looks good to me.  Thanks!

2022-06-14 02:19 UTC, ZeLonewolf commented on CONTRIBUTING.md
> +require a bash analogue][64].)
I think everything after "installed." can be deleted, along with refs 61 and 64.  We don't really need to point out the history of how we got here.

2022-06-14 02:53 UTC, bgo-eiu commented
Alright then - removed to keep things simple.

2022-06-14 02:53 UTC, ZeLonewolf approved these changes
Looks good to me 🎉

2022-06-14 17:42 UTC, merged