Icelandic shields
ZeLonewolf/openstreetmap-americana pull request #438
Opened 2022-06-19 17:26 UTC by riiga

Adds support for Icelandic shields as per issue #390.

I only added the main network values, not any of the combinations, but this covers 90-something % of all roads. If we could get the Icelandic community to prefix these with `IS:`, full support could be added since all shields look the same. It might also be a good idea to suggest ordering the combinations so that `S;T;L` and `T;S;L` are equivalent and only written as `S;T;L`.

2022-06-19 17:35 UTC, ZeLonewolf commented
Supporting unprefixed single-letter network values seems particularly problematic.

2022-06-19 17:44 UTC, claysmalley commented
`Sx` is the same as the country code for the Dutch part of Saint Martin. We cannot add support for these shields until the Icelandic community determines a new `network=*` tagging scheme that does not collide with any other countries.

2022-06-19 18:21 UTC, ZeLonewolf requested changes
1. Coordinate with the mapping community in Iceland to define `network` values consistent with international norms
2. Update this PR consistent with those definitions.

2022-06-20 06:30 UTC, riiga commented on src/js/shield_defs.js
> +    //"T;S;L",
From what I can deduce, it's the latter: the classification of the road changes, but it has the same number (and shield). Hence why, if we could just prefix with `IS:`, the rest of the network won't matter as there's only one type of shield in use.

2022-06-20 11:58 UTC, ZeLonewolf commented
I've been to Iceland, and in my experience there are only two kinds of routes: roads and F roads.   The network of one to three digit roads, generally with black on white colors, has no on the ground differentiation that I can see. 

Image below, the dashed border means a road to that numbered route. 

![is_41.jpg](https://user-images.githubusercontent.com/3254090/174595932-a3c2d815-e5ad-466d-8b3b-daaa6d25ab93.jpg)

The other type, F roads, have the same visuals but are prefixed with F.  They indicate mountain roads and are seasonal and require an off road vehicle. Fords and difficult terrain are typical. 

![is_f88.jpg](https://user-images.githubusercontent.com/3254090/174596423-0c79ce32-da1f-4dbd-b3cf-f27482107d9f.jpg)

2022-06-20 17:19 UTC, 1ec5 commented
> Image below, the dashed border means a road to that numbered route.

This would be a third route type, right? Several Scandinavian countries apparently denote link roads with dashed borders.

2022-06-21 00:13 UTC, claysmalley commented
According to the [OSM Wiki](https://wiki.openstreetmap.org/wiki/Icelandic_road_system), the current `network=*` tagging scheme in Iceland seems to represent functional classification. This scheme can be seen [here](https://www.vegagerdin.is/vegakerfid/vegaskra/) (click on the image on the right, or the PDF link at the bottom).

Shields in Iceland may all be identical, though it appears many are unsigned. I see many routes with 4-digit numbers but it looks like only routes with 1-3 digits (and maybe an `F` prefix) have signs on the ground.

2022-06-21 07:58 UTC, riiga commented
I've sent a mail to the mailing list.
https://lists.openstreetmap.org/pipermail/talk-is/2022-June/001077.html

2022-06-21 09:33 UTC, 1ec5 commented
Is it even necessary to mention the classification in the `network` value? In other words, when someone refers to the route as a whole, do they call it “Tengivegur/Landsvegur 22”? (I’m making up the number here.) Or is it actually two distinct routes, “Tengivegur 22” and “Landsvegur 22”, that happen to share the same number and connect to one another?

2022-07-07 13:52 UTC, ZeLonewolf commented
Seeing as there doesn't seem to be much if any in the way of local engagement, from everything I've read and based on my on the ground experience driving around the country for a week or so, here's my hot take:

There is one, single, numbered national road network in Iceland, and the functional classifications are a separate concept.  I'm inclined to think that the most sensible scheme for route relations for Icelandic roads is:
`network=IS`
`ref=<route number>`

The only thing that comes close to being a separate network are the "F" roads, but they're consistent with the other non-F roads in their numbering scheme and signage.

2022-07-08 07:01 UTC, riiga commented
I'm inclined to agree. If no one objects, I will move the current data contained in the network tag to `road_class` and then use `network=IS` for all relations.

2022-07-09 06:27 UTC, 1ec5 commented
> I'm inclined to agree. If no one objects, I will move the current data contained in the network tag to `road_class` (or any better suggestion) and then use `network=IS` for all relations.

Note that “road class” is sometimes used to describe the `highway` key. There’s precedent for putting official road classifications in [`designation`](https://wiki.openstreetmap.org/wiki/Key:designation), but there are also plenty of examples of countries that have devised country-specific keys for this purpose.

2022-07-09 09:00 UTC, riiga commented
Designation seems to be the key I was looking for

2022-07-10 15:37 UTC, riiga commented
[Brace for impact](https://www.openstreetmap.org/changeset/123437050)

2022-07-10 16:24 UTC, claysmalley commented
Don't forget `npm run status_map` to add Iceland to the shield coverage map.

2022-07-11 01:16 UTC, ZeLonewolf commented
That must have been quite the effort @riiga 
![image](https://user-images.githubusercontent.com/3254090/178171193-65e52a8f-f6b8-4a7d-a5e6-860b33cc874b.png)

I will update this PR when I can get around to re-rendering the planet.

2022-07-11 06:50 UTC, riiga commented
@ZeLonewolf Overpass-Turbo + JOSM made quick work of it, though I did run out of memory a couple of times in JOSM (remember to disable validator checks on upload when working with large amounts of data).

2022-07-14 00:11 UTC, 1ec5 approved these changes

2022-07-21 02:33 UTC, 1ec5 commented
[<img src="https://user-images.githubusercontent.com/1231218/180117407-a5bf77e7-d9a6-4067-b888-7e8a5d77d66e.png" width="400" alt="1, 60, 528">](https://zelonewolf.github.io/openstreetmap-americana/#12.68/64.80019/-21.46465)

2022-07-21 02:35 UTC, merged