Add shield for NZ:WRR
ZeLonewolf/openstreetmap-americana pull request #529
Opened 2022-08-01 23:58 UTC by k-yle

This PR adds a shield for `network=NZ:WRR`, which is a one-of-a-kind route ([example 1](https://www.nzta.govt.nz/media-releases/new-logo-to-guide-motorists-on-western-ring-route/), [example 2](https://goo.gl/maps/4Thd4qVTCpHrtQmo6))

Related to #451

2022-08-02 00:06 UTC, ZeLonewolf commented
Thanks @k-yle for opening a PR.

Looking at this image:
![image](https://user-images.githubusercontent.com/3254090/182264785-4daee18f-ce5f-4a19-86ca-c474d572a22e.png)

I have questions.

Is the WRR route relation separate from the route 18 relation?  I would think that we would want a custom graphic for the route, much like we do for special turnpikes in the United States.  This PR declares a pill shield, which draws a circle or pill around the value in `ref`, and I'm not sure that's really the behavior we're looking for here?

2022-08-02 00:19 UTC, k-yle commented
yes, it's separate from SH 18, ([this is the OSM relation](https://osm.org/relation/13730708)). I saw that `US:IA` uses the same style, and [renders similarly](https://zelonewolf.github.io/openstreetmap-americana/#13.81/42.22584/-91.86094) to how the WR shields are signposted. 

I wasn't sure if a custom graphic was appropriate in this case (?), since it's a pretty much just a circle with text inside.

2022-08-02 00:24 UTC, ZeLonewolf commented
Oh, I see.  Black on white WR in a pill does seem like a workable approximation in that case.

2022-08-02 00:30 UTC, ZeLonewolf commented
Code looks essentially correct, needs a tile update to test.

2022-08-02 00:32 UTC, claysmalley requested changes
I think the plain text approach is reasonable, though it at least seems important that the shield is a circle rather than a pill or oval. If we use `ovalShield()` and specify a width of 20 it should make the shield circular.

2022-08-02 00:32 UTC, claysmalley commented on src/js/shield_defs.js
> +  shields["NZ:WRR"] = pillShield(Color.shields.white, Color.shields.black);
```suggestion
  shields["NZ:WRR"] = ovalShield(Color.shields.white, Color.shields.black, Color.shields.black, 20);
```

2022-08-16 21:59 UTC, claysmalley approved these changes
Looks good!

![Screenshot from 2022-08-16 17-58-41](https://user-images.githubusercontent.com/1732117/184992566-41373dfd-382d-40ff-9a5b-57d9adceb1e9.png)

2022-08-17 16:08 UTC, merged

2022-08-17 16:08 UTC, ZeLonewolf commented
Thanks @k-yle for your contribution!