Add debug variable to specify shield text halo color
ZeLonewolf/openstreetmap-americana pull request #549
Opened 2022-09-03 22:15 UTC by claysmalley

Adds a debug variable that overrides the text halo color on shields. This can be helpful to ensure text doesn't collide with other design features when determining padding values for shield definitions.

```
const SHIELD_TEXT_HALO_COLOR = null;
```
![Screenshot from 2022-09-03 18-11-58](https://user-images.githubusercontent.com/1732117/188289114-a3dd2370-9b45-4207-8249-e615ab0a652e.png)
```
const SHIELD_TEXT_HALO_COLOR = "magenta";
```
![Screenshot from 2022-09-03 18-12-14](https://user-images.githubusercontent.com/1732117/188289116-ac12f46b-05f0-47b3-9e7d-c2fa6c465cce.png)

2022-09-03 22:56 UTC, ZeLonewolf requested changes
Looks good, and tested satisfactorily.

Can we add something in the shield contributor's guide that describes the use of this variable?

2022-09-04 14:34 UTC, claysmalley commented
Added a blurb in the documentation.

2022-09-09 01:40 UTC, zekefarwell commented on src/configs/config.aws.js
> +const SHIELD_TEXT_HALO_COLOR = null;
I'd suggest we briefly document the purpose and usage of the variable with a comment.  Prefilling with a useful value and then commenting it out also might be nice.  Then you just have to un-comment to turn this debug feature on.

```suggestion

// Uncomment this variable to override the shield text halo color.  Useful while testing shield design changes.
// Accepts an HTML color name, hex code, or other CSS color value.
//const SHIELD_TEXT_HALO_COLOR = "magenta";
```

I'd also suggest the variable be named a bit more descriptively so it's clear this is a debug/override/test feature, not something that gets used in production.  `SHIELD_TEXT_HALO_COLOR_DEBUG_OVERRIDE` is rather long long.  Maybe just `SHIELD_TEXT_HALO_COLOR_OVERRIDE`?

2022-09-10 01:22 UTC, zekefarwell approved these changes
Oh right, the variable has to be commented/uncommented in the export block as well.  
https://github.com/ZeLonewolf/openstreetmap-americana/blob/239d9f0003752e645c8208f4156e2657a579dc3f/src/configs/config.aws.js#L9-L18
I guesshaving it commented out isn't as clean as I was imagining.  Maybe it was better having it just default to null.   Either way , this all looks good to me.

2022-09-11 01:43 UTC, ZeLonewolf approved these changes
Looks good, thanks for the writeup!

2022-09-11 02:11 UTC, merged